"""add location fields to parents and clubs

Revision ID: 6057e1d2d808
Revises: d6c3014e8d03
Create Date: 2026-09-17 12:33:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6057e1d2d808'
down_revision: Union[str, None] = 'd6c3014e8d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('parents', sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parents', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('parents', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'longitude')
    op.drop_column('parents', 'latitude')
    op.drop_column('parents', 'address')
    op.drop_column('clubs', 'longitude')
    op.drop_column('clubs', 'latitude')
    # ### end Alembic commands ###
