"""Add sports wiki and split evaluations

Revision ID: 6190e6c78ba8
Revises: 6057e1d2d808
Create Date: 2026-09-18 12:23:09.012992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6190e6c78ba8'
down_revision: Union[str, None] = '6057e1d2d808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('storytelling_description', sa.String(length=1000), nullable=True),
    sa.Column('fun_facts', sa.String(length=500), nullable=True),
    sa.Column('benefits_summary', sa.String(length=500), nullable=True),
    sa.Column('introductory_video_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('physical_tests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('trimester_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychological_forms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('trimester_id', sa.String(length=50), nullable=False),
    sa.Column('creativity_score', sa.Integer(), nullable=False),
    sa.Column('teamwork_score', sa.Integer(), nullable=False),
    sa.Column('stress_management_score', sa.Integer(), nullable=False),
    sa.Column('coach_notes', sa.String(length=255), nullable=True),
    sa.Column('ai_recommended_sport', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('creativity_score >= 0 AND creativity_score <= 10', name='chk_creativity_valido'),
    sa.CheckConstraint('stress_management_score >= 0 AND stress_management_score <= 10', name='chk_stress_valido'),
    sa.CheckConstraint('teamwork_score >= 0 AND teamwork_score <= 10', name='chk_teamwork_valido'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('evaluations')
    op.add_column('courses', sa.Column('sport_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'courses', 'sports', ['sport_id'], ['id'], ondelete='RESTRICT')
    op.add_column('parents', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.add_column('parents', sa.Column('referred_by_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'parents', ['referral_code'])
    op.create_foreign_key(None, 'parents', 'parents', ['referred_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'referred_by_id')
    op.drop_column('parents', 'referral_code')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'sport_id')
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teamwork_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discipline_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_recommended_sport', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('coach_notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('agility_score >= 0 AND agility_score <= 10', name='chk_agility_valido'),
    sa.CheckConstraint('discipline_score >= 0 AND discipline_score <= 10', name='chk_discipline_valido'),
    sa.CheckConstraint('teamwork_score >= 0 AND teamwork_score <= 10', name='chk_teamwork_valido'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name='evaluations_child_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='evaluations_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evaluations_pkey')
    )
    op.drop_table('psychological_forms')
    op.drop_table('physical_tests')
    op.drop_table('sports')
    # ### end Alembic commands ###
