"""Aggiunti Club, Parent e Child

Revision ID: 9d9094526676
Revises: 6567f2910408
Create Date: 2026-09-01 17:31:15.724316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9094526676'
down_revision: Union[str, None] = '6567f2910408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.add_column('children', sa.Column('date_of_birth', sa.DATE(), nullable=False))
    op.add_column('children', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('children', sa.Column('fiscal_code', sa.String(length=16), nullable=False))
    op.add_column('children', sa.Column('medical_notes', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('children_user_id_fkey'), 'children', type_='foreignkey')
    op.create_foreign_key(None, 'children', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('children', 'user_id')
    op.add_column('clubs', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('clubs', sa.Column('email_contact', sa.String(length=255), nullable=False))
    op.add_column('clubs', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('parents', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('parents', sa.Column('fiscal_code', sa.String(length=16), nullable=False))
    op.drop_column('parents', 'child_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('child_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('parents', 'fiscal_code')
    op.drop_column('parents', 'phone_number')
    op.drop_column('clubs', 'logo_url')
    op.drop_column('clubs', 'email_contact')
    op.drop_column('clubs', 'phone_number')
    op.add_column('children', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.create_foreign_key(op.f('children_user_id_fkey'), 'children', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('children', 'medical_notes')
    op.drop_column('children', 'fiscal_code')
    op.drop_column('children', 'gender')
    op.drop_column('children', 'date_of_birth')
    op.drop_column('children', 'parent_id')
    # ### end Alembic commands ###
