"""remove coach_id from courses

Revision ID: d6c3014e8d03
Revises: 6ad53a79d3dc
Create Date: 2026-09-17 12:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c3014e8d03'
down_revision: Union[str, None] = '6ad53a79d3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_coach_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key('courses_coach_id_fkey', 'courses', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
